version: "3.3"

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=
      - DHIS2_ANALYTICS_API_URL=
      - DHIS2_USERNAME=
      - DHIS2_PASSWORD=
    volumes:
      - ".images:/app/images"
    restart: always